// One-command environment setup. Creates the two env files the app needs
// (if they don't already exist) with a freshly generated AUTH_SECRET.
// Safe to re-run: existing files are never overwritten.
import { existsSync, writeFileSync, mkdirSync } from "fs";
import { randomBytes } from "crypto";
import path from "path";
import { fileURLToPath } from "url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const authSecret = randomBytes(32).toString("base64url");

const webEnvPath = path.join(root, "apps", "web", ".env.local");
const dbEnvPath = path.join(root, "packages", "db", ".env");

const webEnv = `# Generated by scripts/setup.mjs - safe to edit.
DATABASE_URL="file:./dev.db"
AUTH_SECRET="${authSecret}"
# Add your Anthropic API key to enable the AI tutor, quiz generation,
# and AI grading: https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=""
`;

const dbEnv = `# Generated by scripts/setup.mjs - used by Prisma CLI commands.
DATABASE_URL="file:./dev.db"
`;

let created = 0;
if (!existsSync(webEnvPath)) {
  mkdirSync(path.dirname(webEnvPath), { recursive: true });
  writeFileSync(webEnvPath, webEnv);
  console.log(`created  ${path.relative(root, webEnvPath)}`);
  created++;
} else {
  console.log(`exists   ${path.relative(root, webEnvPath)} (left untouched)`);
}
if (!existsSync(dbEnvPath)) {
  mkdirSync(path.dirname(dbEnvPath), { recursive: true });
  writeFileSync(dbEnvPath, dbEnv);
  console.log(`created  ${path.relative(root, dbEnvPath)}`);
  created++;
} else {
  console.log(`exists   ${path.relative(root, dbEnvPath)} (left untouched)`);
}

console.log(`
${created > 0 ? "Environment files ready." : "Environment already set up."}
Next steps:
  1. npm run db:setup     (create + seed the database)
  2. npm run dev          (start the web app at http://localhost:3000)
  3. Optional: add your ANTHROPIC_API_KEY to apps/web/.env.local
     to enable the AI tutor. Demo login: alex@demo.edu / coursemind
`);
