// School recognition: resolve an email domain to the school's real name,
// so "alex@stanford.edu" lands in "Stanford University", not "Stanford
// (stanford.edu)". Curated map of well-known domains worldwide; unknown
// domains fall back to the old prettified label. Lookups also strip
// subdomains ("cs.stanford.edu" -> "stanford.edu") so departmental email
// addresses land in the same school.
//
// Names here are AUTHORITATIVE: resolveUniversityId self-heals an existing
// University row's name when its domain is in this map (and never touches
// rows for unknown domains, so hand-named spaces like the demo university
// survive).

const KNOWN_UNIVERSITIES: Record<string, string> = {
  // ---- United States ----
  "mit.edu": "Massachusetts Institute of Technology",
  "stanford.edu": "Stanford University",
  "harvard.edu": "Harvard University",
  "yale.edu": "Yale University",
  "princeton.edu": "Princeton University",
  "columbia.edu": "Columbia University",
  "upenn.edu": "University of Pennsylvania",
  "brown.edu": "Brown University",
  "dartmouth.edu": "Dartmouth College",
  "cornell.edu": "Cornell University",
  "caltech.edu": "California Institute of Technology",
  "cmu.edu": "Carnegie Mellon University",
  "uchicago.edu": "University of Chicago",
  "duke.edu": "Duke University",
  "northwestern.edu": "Northwestern University",
  "jhu.edu": "Johns Hopkins University",
  "rice.edu": "Rice University",
  "vanderbilt.edu": "Vanderbilt University",
  "nyu.edu": "New York University",
  "usc.edu": "University of Southern California",
  "georgetown.edu": "Georgetown University",
  "nd.edu": "University of Notre Dame",
  "emory.edu": "Emory University",
  "tufts.edu": "Tufts University",
  "bu.edu": "Boston University",
  "northeastern.edu": "Northeastern University",
  "bc.edu": "Boston College",
  "rochester.edu": "University of Rochester",
  "case.edu": "Case Western Reserve University",
  "gatech.edu": "Georgia Institute of Technology",
  "purdue.edu": "Purdue University",
  "illinois.edu": "University of Illinois Urbana-Champaign",
  "umich.edu": "University of Michigan",
  "wisc.edu": "University of Wisconsin-Madison",
  "umn.edu": "University of Minnesota",
  "osu.edu": "The Ohio State University",
  "psu.edu": "Penn State University",
  "rutgers.edu": "Rutgers University",
  "umd.edu": "University of Maryland",
  "virginia.edu": "University of Virginia",
  "unc.edu": "University of North Carolina at Chapel Hill",
  "ufl.edu": "University of Florida",
  "utexas.edu": "The University of Texas at Austin",
  "tamu.edu": "Texas A&M University",
  "asu.edu": "Arizona State University",
  "arizona.edu": "University of Arizona",
  "colorado.edu": "University of Colorado Boulder",
  "washington.edu": "University of Washington",
  "uw.edu": "University of Washington",
  "oregonstate.edu": "Oregon State University",
  "uoregon.edu": "University of Oregon",
  "utah.edu": "University of Utah",
  "iu.edu": "Indiana University",
  "msu.edu": "Michigan State University",
  "pitt.edu": "University of Pittsburgh",
  "gwu.edu": "George Washington University",
  "american.edu": "American University",
  "syr.edu": "Syracuse University",
  "villanova.edu": "Villanova University",
  "fordham.edu": "Fordham University",
  "smu.edu": "Southern Methodist University",
  "baylor.edu": "Baylor University",
  "tulane.edu": "Tulane University",
  "wustl.edu": "Washington University in St. Louis",
  "vt.edu": "Virginia Tech",
  "ncsu.edu": "North Carolina State University",
  "uga.edu": "University of Georgia",
  "clemson.edu": "Clemson University",
  "auburn.edu": "Auburn University",
  "ua.edu": "University of Alabama",
  "lsu.edu": "Louisiana State University",
  "ku.edu": "University of Kansas",
  "unl.edu": "University of Nebraska-Lincoln",
  "iastate.edu": "Iowa State University",
  "uiowa.edu": "University of Iowa",
  "mizzou.edu": "University of Missouri",
  "ucla.edu": "University of California, Los Angeles",
  "berkeley.edu": "University of California, Berkeley",
  "ucsd.edu": "University of California, San Diego",
  "ucdavis.edu": "University of California, Davis",
  "uci.edu": "University of California, Irvine",
  "ucsb.edu": "University of California, Santa Barbara",
  "ucsc.edu": "University of California, Santa Cruz",
  "ucr.edu": "University of California, Riverside",
  "ucmerced.edu": "University of California, Merced",
  "calpoly.edu": "Cal Poly San Luis Obispo",
  "sjsu.edu": "San Jose State University",
  "sdsu.edu": "San Diego State University",
  "csulb.edu": "California State University, Long Beach",
  "fsu.edu": "Florida State University",
  "ucf.edu": "University of Central Florida",
  "usf.edu": "University of South Florida",
  "miami.edu": "University of Miami",
  "gmu.edu": "George Mason University",
  "temple.edu": "Temple University",
  "drexel.edu": "Drexel University",
  "rpi.edu": "Rensselaer Polytechnic Institute",
  "stevens.edu": "Stevens Institute of Technology",
  "rit.edu": "Rochester Institute of Technology",
  "wpi.edu": "Worcester Polytechnic Institute",
  "umass.edu": "University of Massachusetts Amherst",
  "uconn.edu": "University of Connecticut",
  "buffalo.edu": "University at Buffalo",
  "stonybrook.edu": "Stony Brook University",
  "binghamton.edu": "Binghamton University",
  "albany.edu": "University at Albany",
  "depaul.edu": "DePaul University",
  "luc.edu": "Loyola University Chicago",
  "marquette.edu": "Marquette University",
  "byu.edu": "Brigham Young University",
  "unlv.edu": "University of Nevada, Las Vegas",
  "unm.edu": "University of New Mexico",
  "ou.edu": "University of Oklahoma",
  "okstate.edu": "Oklahoma State University",
  "uark.edu": "University of Arkansas",
  "olemiss.edu": "University of Mississippi",
  "utk.edu": "University of Tennessee, Knoxville",
  "uky.edu": "University of Kentucky",
  "wvu.edu": "West Virginia University",
  "udel.edu": "University of Delaware",
  "unh.edu": "University of New Hampshire",
  "uvm.edu": "University of Vermont",
  "maine.edu": "University of Maine",
  "uri.edu": "University of Rhode Island",
  "hawaii.edu": "University of Hawaiʻi",
  "alaska.edu": "University of Alaska",
  "howard.edu": "Howard University",
  "morehouse.edu": "Morehouse College",
  "spelman.edu": "Spelman College",
  "wellesley.edu": "Wellesley College",
  "amherst.edu": "Amherst College",
  "williams.edu": "Williams College",
  "swarthmore.edu": "Swarthmore College",
  "pomona.edu": "Pomona College",
  "middlebury.edu": "Middlebury College",
  "oberlin.edu": "Oberlin College",
  "reed.edu": "Reed College",
  "vassar.edu": "Vassar College",

  // ---- Canada ----
  "utoronto.ca": "University of Toronto",
  "mail.utoronto.ca": "University of Toronto",
  "ubc.ca": "University of British Columbia",
  "mcgill.ca": "McGill University",
  "uwaterloo.ca": "University of Waterloo",
  "ualberta.ca": "University of Alberta",
  "mcmaster.ca": "McMaster University",
  "queensu.ca": "Queen's University",
  "uottawa.ca": "University of Ottawa",
  "yorku.ca": "York University",
  "sfu.ca": "Simon Fraser University",
  "uvic.ca": "University of Victoria",
  "ucalgary.ca": "University of Calgary",
  "umontreal.ca": "Université de Montréal",
  "concordia.ca": "Concordia University",
  "dal.ca": "Dalhousie University",
  "uwo.ca": "Western University",
  "umanitoba.ca": "University of Manitoba",
  "usask.ca": "University of Saskatchewan",
  "carleton.ca": "Carleton University",
  "torontomu.ca": "Toronto Metropolitan University",

  // ---- United Kingdom & Ireland ----
  "ox.ac.uk": "University of Oxford",
  "cam.ac.uk": "University of Cambridge",
  "imperial.ac.uk": "Imperial College London",
  "ucl.ac.uk": "University College London",
  "lse.ac.uk": "London School of Economics",
  "kcl.ac.uk": "King's College London",
  "ed.ac.uk": "University of Edinburgh",
  "manchester.ac.uk": "University of Manchester",
  "bristol.ac.uk": "University of Bristol",
  "warwick.ac.uk": "University of Warwick",
  "gla.ac.uk": "University of Glasgow",
  "bham.ac.uk": "University of Birmingham",
  "leeds.ac.uk": "University of Leeds",
  "sheffield.ac.uk": "University of Sheffield",
  "nottingham.ac.uk": "University of Nottingham",
  "soton.ac.uk": "University of Southampton",
  "durham.ac.uk": "Durham University",
  "st-andrews.ac.uk": "University of St Andrews",
  "qmul.ac.uk": "Queen Mary University of London",
  "york.ac.uk": "University of York",
  "exeter.ac.uk": "University of Exeter",
  "bath.ac.uk": "University of Bath",
  "lancaster.ac.uk": "Lancaster University",
  "cardiff.ac.uk": "Cardiff University",
  "abdn.ac.uk": "University of Aberdeen",
  "strath.ac.uk": "University of Strathclyde",
  "tcd.ie": "Trinity College Dublin",
  "ucd.ie": "University College Dublin",
  "ucc.ie": "University College Cork",

  // ---- Australia & New Zealand ----
  "unimelb.edu.au": "University of Melbourne",
  "student.unimelb.edu.au": "University of Melbourne",
  "sydney.edu.au": "University of Sydney",
  "unsw.edu.au": "UNSW Sydney",
  "anu.edu.au": "Australian National University",
  "uq.edu.au": "University of Queensland",
  "monash.edu": "Monash University",
  "uwa.edu.au": "University of Western Australia",
  "adelaide.edu.au": "University of Adelaide",
  "uts.edu.au": "University of Technology Sydney",
  "rmit.edu.au": "RMIT University",
  "auckland.ac.nz": "University of Auckland",
  "otago.ac.nz": "University of Otago",
  "canterbury.ac.nz": "University of Canterbury",
  "vuw.ac.nz": "Victoria University of Wellington",

  // ---- South Korea ----
  "snu.ac.kr": "Seoul National University",
  "kaist.ac.kr": "KAIST",
  "yonsei.ac.kr": "Yonsei University",
  "korea.ac.kr": "Korea University",
  "postech.ac.kr": "POSTECH",
  "skku.edu": "Sungkyunkwan University",
  "hanyang.ac.kr": "Hanyang University",
  "khu.ac.kr": "Kyung Hee University",
  "sogang.ac.kr": "Sogang University",
  "ewha.ac.kr": "Ewha Womans University",
  "cau.ac.kr": "Chung-Ang University",
  "hufs.ac.kr": "Hankuk University of Foreign Studies",
  "unist.ac.kr": "UNIST",
  "gist.ac.kr": "GIST",
  "pusan.ac.kr": "Pusan National University",
  "knu.ac.kr": "Kyungpook National University",

  // ---- Japan ----
  "u-tokyo.ac.jp": "The University of Tokyo",
  "kyoto-u.ac.jp": "Kyoto University",
  "osaka-u.ac.jp": "Osaka University",
  "tohoku.ac.jp": "Tohoku University",
  "nagoya-u.ac.jp": "Nagoya University",
  "kyushu-u.ac.jp": "Kyushu University",
  "hokudai.ac.jp": "Hokkaido University",
  "titech.ac.jp": "Tokyo Institute of Technology",
  "waseda.jp": "Waseda University",
  "keio.ac.jp": "Keio University",
  "tsukuba.ac.jp": "University of Tsukuba",
  "kobe-u.ac.jp": "Kobe University",
  "hiroshima-u.ac.jp": "Hiroshima University",

  // ---- China, Hong Kong, Taiwan & Singapore ----
  "tsinghua.edu.cn": "Tsinghua University",
  "pku.edu.cn": "Peking University",
  "fudan.edu.cn": "Fudan University",
  "sjtu.edu.cn": "Shanghai Jiao Tong University",
  "zju.edu.cn": "Zhejiang University",
  "ustc.edu.cn": "University of Science and Technology of China",
  "nju.edu.cn": "Nanjing University",
  "whu.edu.cn": "Wuhan University",
  "hit.edu.cn": "Harbin Institute of Technology",
  "hku.hk": "The University of Hong Kong",
  "cuhk.edu.hk": "The Chinese University of Hong Kong",
  "ust.hk": "Hong Kong University of Science and Technology",
  "connect.ust.hk": "Hong Kong University of Science and Technology",
  "polyu.edu.hk": "The Hong Kong Polytechnic University",
  "cityu.edu.hk": "City University of Hong Kong",
  "ntu.edu.tw": "National Taiwan University",
  "nthu.edu.tw": "National Tsing Hua University",
  "nycu.edu.tw": "National Yang Ming Chiao Tung University",
  "nus.edu.sg": "National University of Singapore",
  "u.nus.edu": "National University of Singapore",
  "ntu.edu.sg": "Nanyang Technological University",
  "e.ntu.edu.sg": "Nanyang Technological University",
  "smu.edu.sg": "Singapore Management University",
  "sutd.edu.sg": "Singapore University of Technology and Design",

  // ---- Mongolia ----
  "num.edu.mn": "National University of Mongolia",
  "must.edu.mn": "Mongolian University of Science and Technology",
  "msue.edu.mn": "Mongolian National University of Education",
  "mnums.edu.mn": "Mongolian National University of Medical Sciences",
  "ufe.edu.mn": "University of Finance and Economics",
  "muls.edu.mn": "Mongolian University of Life Sciences",

  // ---- Continental Europe ----
  "ethz.ch": "ETH Zurich",
  "epfl.ch": "EPFL",
  "uzh.ch": "University of Zurich",
  "unige.ch": "University of Geneva",
  "tum.de": "Technical University of Munich",
  "lmu.de": "LMU Munich",
  "uni-heidelberg.de": "Heidelberg University",
  "hu-berlin.de": "Humboldt University of Berlin",
  "fu-berlin.de": "Free University of Berlin",
  "tu-berlin.de": "Technical University of Berlin",
  "rwth-aachen.de": "RWTH Aachen University",
  "kit.edu": "Karlsruhe Institute of Technology",
  "uni-bonn.de": "University of Bonn",
  "uni-freiburg.de": "University of Freiburg",
  "uva.nl": "University of Amsterdam",
  "tudelft.nl": "Delft University of Technology",
  "uu.nl": "Utrecht University",
  "leidenuniv.nl": "Leiden University",
  "rug.nl": "University of Groningen",
  "tue.nl": "Eindhoven University of Technology",
  "kuleuven.be": "KU Leuven",
  "ugent.be": "Ghent University",
  "ulb.be": "Université libre de Bruxelles",
  "sorbonne-universite.fr": "Sorbonne University",
  "psl.eu": "PSL University",
  "polytechnique.edu": "École Polytechnique",
  "ens.fr": "École Normale Supérieure",
  "univ-paris-saclay.fr": "Université Paris-Saclay",
  "ku.dk": "University of Copenhagen",
  "dtu.dk": "Technical University of Denmark",
  "aau.dk": "Aalborg University",
  "uio.no": "University of Oslo",
  "ntnu.no": "Norwegian University of Science and Technology",
  "uu.se": "Uppsala University",
  "lu.se": "Lund University",
  "kth.se": "KTH Royal Institute of Technology",
  "su.se": "Stockholm University",
  "chalmers.se": "Chalmers University of Technology",
  "helsinki.fi": "University of Helsinki",
  "aalto.fi": "Aalto University",
  "ut.ee": "University of Tartu",
  "uw.edu.pl": "University of Warsaw",
  "uj.edu.pl": "Jagiellonian University",
  "cuni.cz": "Charles University",
  "cvut.cz": "Czech Technical University in Prague",
  "univie.ac.at": "University of Vienna",
  "tuwien.ac.at": "TU Wien",
  "unibo.it": "University of Bologna",
  "polimi.it": "Politecnico di Milano",
  "uniroma1.it": "Sapienza University of Rome",
  "unipd.it": "University of Padua",
  "ub.edu": "University of Barcelona",
  "uam.es": "Autonomous University of Madrid",
  "ucm.es": "Complutense University of Madrid",
  "upc.edu": "Polytechnic University of Catalonia",
  "tecnico.ulisboa.pt": "Instituto Superior Técnico",
  "up.pt": "University of Porto",
  "uoa.gr": "National and Kapodistrian University of Athens",
  "metu.edu.tr": "Middle East Technical University",
  "boun.edu.tr": "Boğaziçi University",
  "itu.edu.tr": "Istanbul Technical University",
  "ku.edu.tr": "Koç University",
  "sabanciuniv.edu": "Sabancı University",

  // ---- India ----
  "iitb.ac.in": "IIT Bombay",
  "iitd.ac.in": "IIT Delhi",
  "iitm.ac.in": "IIT Madras",
  "iitk.ac.in": "IIT Kanpur",
  "iitkgp.ac.in": "IIT Kharagpur",
  "iisc.ac.in": "Indian Institute of Science",
  "du.ac.in": "University of Delhi",
  "bits-pilani.ac.in": "BITS Pilani",
  "vit.ac.in": "VIT University",

  // ---- Latin America ----
  "usp.br": "University of São Paulo",
  "unicamp.br": "University of Campinas",
  "ufrj.br": "Federal University of Rio de Janeiro",
  "unam.mx": "National Autonomous University of Mexico",
  "tec.mx": "Tecnológico de Monterrey",
  "itesm.mx": "Tecnológico de Monterrey",
  "uba.ar": "University of Buenos Aires",
  "uc.cl": "Pontificia Universidad Católica de Chile",
  "uchile.cl": "University of Chile",
  "uniandes.edu.co": "Universidad de los Andes",

  // ---- Middle East & Africa ----
  "tau.ac.il": "Tel Aviv University",
  "huji.ac.il": "Hebrew University of Jerusalem",
  "technion.ac.il": "Technion - Israel Institute of Technology",
  "aub.edu.lb": "American University of Beirut",
  "aucegypt.edu": "The American University in Cairo",
  "kaust.edu.sa": "KAUST",
  "ku.ac.ae": "Khalifa University",
  "aus.edu": "American University of Sharjah",
  "uct.ac.za": "University of Cape Town",
  "wits.ac.za": "University of the Witwatersrand",
  "up.ac.za": "University of Pretoria",
  "uonbi.ac.ke": "University of Nairobi",
  "ui.edu.ng": "University of Ibadan",
  "unilag.edu.ng": "University of Lagos",
};

/**
 * Look up the official school name for an email domain. Tries the exact
 * domain first, then walks up the subdomains ("mail.cs.stanford.edu" ->
 * "cs.stanford.edu" -> "stanford.edu"). Returns null when unknown.
 */
export function lookupUniversityName(domain: string): string | null {
  const normalized = domain.toLowerCase().trim();
  const labels = normalized.split(".");
  for (let i = 0; i < labels.length - 1; i++) {
    const candidate = labels.slice(i).join(".");
    const name = KNOWN_UNIVERSITIES[candidate];
    if (name) return name;
  }
  return null;
}
